language: rust
cache: cargo
before_script:
  - rustup default nightly-2019-03-23-x86_64-unknown-linux-gnu
  - rustup component add clippy
  - rustup component add rustfmt
rust:
  - nightly
matrix:
  fast_finish: true
script:
  - cargo +nightly-2019-03-23 check
  - cargo +nightly-2019-03-23 clippy --all-features -- -D warnings
  - cargo +nightly-2019-03-23 test --doc
  - cargo +nightly-2019-03-23 test --lib
  - cargo +nightly-2019-03-23 fmt --all -- --check